object Versions {
    
    const val APPCOMPAT = "1.2.0"
    const val CONSTRAINT_LAYOUT = "2.0.4"
    const val COIL = "1.3.2"
    const val CORE_KTX = "1.3.2"
    const val DATA_STORE = "1.0.0"
    const val ESPRESSO = "3.3.0"
    const val FLEX_BOX = "3.0.0"
    const val KOTLIN = "1.6.10"
    const val MATERIAL = "1.3.0"
    const val JUNIT = "1.1.2"
    const val ESPRESSO_CORE = "3.1.0"
    const val NAVIGATION_COMPONENT = "2.3.5"
    const val CORE = "1.3.2"
    const val LIFECYCLE_VERSION_KTX = "2.3.1"
    const val LIFECYCLE_VERSION = "2.2.0"
    const val RUNTIME_KTX = "2.4.0-alpha02"
    const val ARCH_VERSION = "2.1.0"
    const val HILT_VERSION = "2.37"
    const val FRAGMENT_TEST = "1.1.0"
    const val COROUTINES = "1.4.2-native-mt"
    const val MOCKITO = "3.8.0"
    const val TEST_RULES_RUNNER = "1.3.0"
    const val ROOM_VERSION = "2.3.0"
    const val RETROFIT = "2.9.0"
    const val OKHTTP = "4.9.0"
    const val SECURITY_CRYPTO = "1.0.0"
    const val FB_SHIMMER = "0.5.0@aar"
}
